// Copyright (c) 2026 Pratik Kumar. Licensed under the MIT License.

#include "AssimpBlueprintLibrary.h"

#include "AssimpCore.h"
#include "AssimpExporter.h"
#include "AssimpRuntime.h"
#include "AssimpScene.h"
#include "AssimpSceneObject.h"

#include "AssimpSceneTypes.h"
#include "MeshDescription.h"
#include "Camera/CameraComponent.h"
#include "Components/DirectionalLightComponent.h"
#include "Components/DynamicMeshComponent.h"
#include "Components/PointLightComponent.h"
#include "Components/SpotLightComponent.h"
#include "GameFramework/Actor.h"
#include "Engine/Texture2D.h"
#include "Materials/Material.h"
#include "Materials/MaterialInstanceDynamic.h"
#include "Materials/MaterialInterface.h"
// EMaterialDomain / MD_Surface. UE5 moved these out of Material.h, and the editor's unity build
// happens to pull them in transitively -- an isolated packaging build does not.
#include "MaterialDomain.h"
#include "UDynamicMesh.h"

namespace AssimpRuntimePrivate
{
	/**
	 * Assigns one material slot per source mesh on a spawned component.
	 *
	 * Assigning something is mandatory, not cosmetic. A primitive with no material slots yields an
	 * empty FMaterialRelevance, and the renderer then gives the proxy no pass flags -- so the
	 * geometry is not drawn at all, despite the component being registered, visible, and holding a
	 * valid mesh with correct bounds. (The scene proxy's own GetMaterial does substitute the default
	 * material, which is why this looks like it ought to render; relevance is computed from the
	 * component's slot count, not from that substitution.)
	 *
	 * @param Component     Component to configure.
	 * @param SceneObject   Scene the meshes came from; used to create textures on demand.
	 * @param Info          Scene description, for the per-mesh material indices.
	 * @param MeshIndices   Source meshes backing this component, in polygon-group order. Slot i
	 *                      corresponds to MeshIndices[i], matching how FAssimpMeshConverter emits
	 *                      one polygon group per source mesh.
	 * @param BaseMaterial  Material to instance per slot, or null for the engine default.
	 */
	/**
	 * The plugin's own material, which exposes the texture and scalar parameters
	 * AssignMaterialSlots writes to.
	 *
	 * Generated by Scripts/GenerateDefaultMaterial.py; that script and the parameter names below are
	 * two halves of one contract.
	 */
	const TCHAR* const DefaultMaterialPath = TEXT("/AssimpForUnreal/M_AssimpDefault.M_AssimpDefault");

	/**
	 * Loads the plugin's default material, or null if it is unavailable.
	 *
	 * Resolved once and cached. Returning null is not fatal: the caller falls back to the engine's
	 * default surface material, which renders geometry as flat grey rather than nothing.
	 */
	UMaterialInterface* GetPluginDefaultMaterial()
	{
		static bool bAttempted = false;
		static TWeakObjectPtr<UMaterialInterface> Cached;

		if (Cached.IsValid())
		{
			return Cached.Get();
		}

		// Retry after a failed attempt only if the weak pointer merely went stale, not if the asset
		// was genuinely missing -- otherwise a missing asset means a load attempt per component.
		if (bAttempted && !Cached.IsStale())
		{
			return nullptr;
		}

		bAttempted = true;

		UMaterialInterface* Material =
			LoadObject<UMaterialInterface>(nullptr, DefaultMaterialPath);

		if (Material == nullptr)
		{
			UE_LOG(LogAssimpRuntime, Warning,
				TEXT("Could not load '%s'; imported meshes will use the engine's default material ")
				TEXT("and will not show their textures. Regenerate it with ")
				TEXT("Scripts/GenerateDefaultMaterial.py."),
				DefaultMaterialPath);
			return nullptr;
		}

		Cached = Material;
		return Material;
	}

	void AssignMaterialSlots(
		UDynamicMeshComponent* Component,
		UAssimpSceneObject* SceneObject,
		const FAssimpSceneInfo& Info,
		TArrayView<const int32> MeshIndices,
		UMaterialInterface* BaseMaterial)
	{
		if (Component == nullptr || SceneObject == nullptr || MeshIndices.IsEmpty())
		{
			return;
		}

		// Fall back to the plugin's own material when the caller supplies none, so textures appear
		// with no setup. The engine's default material is the last resort: it has no parameters, so
		// nothing can be bound to it and the model renders flat grey.
		if (BaseMaterial == nullptr)
		{
			BaseMaterial = GetPluginDefaultMaterial();
		}

		UMaterialInterface* Fallback = UMaterial::GetDefaultMaterial(MD_Surface);

		Component->SetNumMaterials(MeshIndices.Num());

		for (int32 SlotIndex = 0; SlotIndex < MeshIndices.Num(); ++SlotIndex)
		{
			const int32 MeshIndex = MeshIndices[SlotIndex];
			const int32 MaterialIndex = Info.Meshes.IsValidIndex(MeshIndex)
				? Info.Meshes[MeshIndex].MaterialIndex
				: INDEX_NONE;

			if (BaseMaterial == nullptr)
			{
				Component->SetMaterial(SlotIndex, Fallback);
				continue;
			}

			UMaterialInstanceDynamic* Instance =
				UMaterialInstanceDynamic::Create(BaseMaterial, Component);
			if (Instance == nullptr)
			{
				Component->SetMaterial(SlotIndex, Fallback);
				continue;
			}

			if (Info.Materials.IsValidIndex(MaterialIndex))
			{
				const FAssimpMaterialInfo& Material = Info.Materials[MaterialIndex];

				// Setting a parameter the material does not declare is a silent no-op, so these can
				// be applied unconditionally rather than probed for first.
				Instance->SetVectorParameterValue(TEXT("BaseColor"), Material.BaseColor);
				Instance->SetVectorParameterValue(TEXT("EmissiveColor"), Material.EmissiveColor);
				Instance->SetScalarParameterValue(TEXT("Metallic"), Material.Metallic);
				Instance->SetScalarParameterValue(TEXT("Roughness"), Material.Roughness);
				Instance->SetScalarParameterValue(TEXT("Opacity"), Material.Opacity);

				// Specular is normal-incidence reflectance / 0.08 in Unreal, so 0.5 is the neutral
				// dielectric value rather than "half". FAssimpMaterialInfo already carries it in
				// that convention, whatever the source model used, so it passes straight through.
				Instance->SetScalarParameterValue(TEXT("Specular"), Material.Specular);

				// Textures, keyed by the parameter names the base material is expected to expose.
				// Loading is lazy and cached per source image inside the scene object, so a model
				// whose many materials share a few images decodes each image once.
				//
				// Each map also has a companion "Use...Texture" scalar. Setting the texture alone is
				// not enough: an unbound TextureSampleParameter2D still samples its default texture,
				// so a material that supplies no emissive map would emit whatever that default holds
				// -- white emissive washes the whole model out. The scalar drives a Lerp in
				// M_AssimpDefault that ignores the sampler entirely when nothing was bound. It has
				// to be a scalar rather than a static switch, because a dynamic material instance
				// cannot change static switches at runtime.
				struct FTextureBinding
				{
					EAssimpTextureSlot Slot;
					const TCHAR* TextureParameter;
					const TCHAR* UseParameter;
				};

				static const FTextureBinding TextureBindings[] = {
					{ EAssimpTextureSlot::BaseColor,        TEXT("BaseColorTexture"), TEXT("UseBaseColorTexture") },
					{ EAssimpTextureSlot::Normal,           TEXT("NormalTexture"),    nullptr /* flat-normal default is the no-op */ },
					{ EAssimpTextureSlot::Roughness,        TEXT("RoughnessTexture"), TEXT("UseRoughnessTexture") },
					{ EAssimpTextureSlot::Metallic,         TEXT("MetallicTexture"),  TEXT("UseMetallicTexture")  },
					{ EAssimpTextureSlot::Specular,         TEXT("SpecularTexture"),  TEXT("UseSpecularTexture")  },
					{ EAssimpTextureSlot::AmbientOcclusion, TEXT("OcclusionTexture"), TEXT("UseOcclusionTexture") },
					{ EAssimpTextureSlot::Emissive,         TEXT("EmissiveTexture"),  TEXT("UseEmissiveTexture")  },
				};

				for (const FTextureBinding& Binding : TextureBindings)
				{
					UTexture2D* Texture =
						SceneObject->CreateTextureForMaterialSlot(MaterialIndex, Binding.Slot);

					if (Texture != nullptr)
					{
						Instance->SetTextureParameterValue(FName(Binding.TextureParameter), Texture);
					}

					if (Binding.UseParameter != nullptr)
					{
						Instance->SetScalarParameterValue(
							FName(Binding.UseParameter), Texture != nullptr ? 1.0f : 0.0f);
					}
				}

				// Alpha cut-out only for materials that actually declare transparency. Driving the
				// opacity mask unconditionally would eat away opaque models whose base-colour PNGs
				// happen to carry a meaningless alpha channel.
				const bool bUseOpacityMask =
					Material.bIsTranslucent ||
					Material.Textures.Contains(EAssimpTextureSlot::Opacity);

				Instance->SetScalarParameterValue(
					TEXT("UseOpacityMask"), bUseOpacityMask ? 1.0f : 0.0f);
			}

			Component->SetMaterial(SlotIndex, Instance);
		}
	}

	/**
	 * Turns a light's physical falloff into the cutoff radius Unreal actually uses.
	 *
	 * The two models do not correspond. Assimp reports the classic constant/linear/quadratic triple,
	 * which describes how brightness decays and never quite reaches zero; Unreal takes a radius at
	 * which the light simply stops being evaluated. Converting means choosing where "dark enough"
	 * is, so this solves for the distance at which the falloff divisor reaches 256 -- the point at
	 * which an 8-bit channel has nothing left to show.
	 *
	 * @param Light         Light to convert.
	 * @param AppliedScale  Scene scale, because the coefficients are in source units and the radius
	 *                      must come out in Unreal ones.
	 * @return              A radius in Unreal units, or 0 when the file gave nothing to work with
	 *                      and the component's own default should stand.
	 */
	float ComputeAttenuationRadius(const FAssimpLightInfo& Light, float AppliedScale)
	{
		const float Constant = FMath::Max(Light.AttenuationConstant, 0.0f);
		const float Linear = FMath::Max(Light.AttenuationLinear, 0.0f);
		const float Quadratic = FMath::Max(Light.AttenuationQuadratic, 0.0f);

		// Constant-only attenuation never decays with distance, so there is no radius to derive.
		if (Linear <= UE_SMALL_NUMBER && Quadratic <= UE_SMALL_NUMBER)
		{
			return 0.0f;
		}

		constexpr float CutoffDivisor = 256.0f;
		const float Target = CutoffDivisor - Constant;
		if (Target <= 0.0f)
		{
			// Already below the threshold at zero distance: a degenerate light, not a tiny one.
			return 0.0f;
		}

		float DistanceInSourceUnits = 0.0f;

		if (Quadratic > UE_SMALL_NUMBER)
		{
			// Quadratic * d^2 + Linear * d - Target = 0, positive root.
			const float Discriminant = Linear * Linear + 4.0f * Quadratic * Target;
			DistanceInSourceUnits = (-Linear + FMath::Sqrt(Discriminant)) / (2.0f * Quadratic);
		}
		else
		{
			DistanceInSourceUnits = Target / Linear;
		}

		const float Radius = DistanceInSourceUnits * FMath::Max(AppliedScale, UE_SMALL_NUMBER);

		return FMath::IsFinite(Radius) ? FMath::Max(Radius, 0.0f) : 0.0f;
	}

	/** Copies the parts of an FAssimpLoadResult that Blueprint should see. */
	FAssimpRuntimeImportResult ConvertResult(const FAssimpLoadResult& LoadResult)
	{
		FAssimpRuntimeImportResult Result;
		Result.bSucceeded = LoadResult.bSucceeded;
		Result.bCancelled = LoadResult.bCancelled;
		Result.ErrorMessage = LoadResult.ErrorMessage;
		Result.ElapsedSeconds = static_cast<float>(LoadResult.ElapsedSeconds);

		// Only warnings are surfaced. Info-level diagnostics are numerous and belong in the log, and
		// errors are already carried by ErrorMessage.
		for (const FAssimpDiagnostic& Diagnostic : LoadResult.Diagnostics)
		{
			if (Diagnostic.Severity == EAssimpDiagnosticSeverity::Warning)
			{
				Result.Warnings.Add(Diagnostic.Message);
			}
		}

		return Result;
	}
}

UAssimpSceneObject* UAssimpBlueprintLibrary::ImportSceneFromFile(
	UObject* Outer,
	const FString& FilePath,
	const FAssimpImportSettings& Settings,
	FAssimpRuntimeImportResult& OutResult)
{
	FAssimpLoadResult LoadResult;
	TSharedPtr<FAssimpScene> Scene = FAssimpScene::LoadFromFile(FilePath, Settings, LoadResult);

	OutResult = AssimpRuntimePrivate::ConvertResult(LoadResult);

	if (!Scene.IsValid())
	{
		return nullptr;
	}

	return UAssimpSceneObject::Create(Outer, MoveTemp(Scene));
}

UAssimpSceneObject* UAssimpBlueprintLibrary::ImportSceneFromMemory(
	UObject* Outer,
	const TArray<uint8>& Buffer,
	const FString& FormatHint,
	const FAssimpImportSettings& Settings,
	FAssimpRuntimeImportResult& OutResult)
{
	FAssimpLoadResult LoadResult;
	TSharedPtr<FAssimpScene> Scene = FAssimpScene::LoadFromMemory(
		Buffer,
		FormatHint,
		FString::Printf(TEXT("<memory>.%s"), *FormatHint),
		Settings,
		LoadResult);

	OutResult = AssimpRuntimePrivate::ConvertResult(LoadResult);

	if (!Scene.IsValid())
	{
		return nullptr;
	}

	return UAssimpSceneObject::Create(Outer, MoveTemp(Scene));
}

TArray<UDynamicMeshComponent*> UAssimpBlueprintLibrary::SpawnSceneAsDynamicMeshComponents(
	AActor* Actor,
	UAssimpSceneObject* SceneObject,
	bool bMergeByNode,
	UMaterialInterface* BaseMaterial)
{
	TArray<UDynamicMeshComponent*> Created;

	if (Actor == nullptr)
	{
		UE_LOG(LogAssimpRuntime, Warning, TEXT("SpawnSceneAsDynamicMeshComponents needs an actor."));
		return Created;
	}

	if (SceneObject == nullptr || !SceneObject->IsValidScene())
	{
		UE_LOG(LogAssimpRuntime, Warning, TEXT("SpawnSceneAsDynamicMeshComponents needs a valid scene."));
		return Created;
	}

	const FAssimpSceneInfo& Info = SceneObject->GetSceneInfo();

	USceneComponent* RootComponent = Actor->GetRootComponent();

	// World transforms are accumulated as the hierarchy is walked. FAssimpSceneInfo guarantees a
	// parent precedes its children, so a single forward pass can rely on the parent's world
	// transform already being known.
	TArray<FTransform> WorldTransforms;
	WorldTransforms.SetNum(Info.Nodes.Num());

	for (int32 NodeIndex = 0; NodeIndex < Info.Nodes.Num(); ++NodeIndex)
	{
		const FAssimpNodeInfo& Node = Info.Nodes[NodeIndex];

		WorldTransforms[NodeIndex] = Info.Nodes.IsValidIndex(Node.ParentIndex)
			? Node.LocalTransform * WorldTransforms[Node.ParentIndex]
			: Node.LocalTransform;

		if (Node.MeshIndices.IsEmpty())
		{
			continue;
		}

		// Sanity-check the indices before use: a malformed file can reference meshes that do not
		// exist, and Assimp does not always reject that.
		TArray<int32> ValidMeshIndices;
		ValidMeshIndices.Reserve(Node.MeshIndices.Num());
		for (const int32 MeshIndex : Node.MeshIndices)
		{
			if (Info.Meshes.IsValidIndex(MeshIndex))
			{
				ValidMeshIndices.Add(MeshIndex);
			}
		}

		if (ValidMeshIndices.IsEmpty())
		{
			continue;
		}

		// Merging is the better default. Assimp splits geometry by material, so without it a simple
		// object with three materials becomes three components -- three draw calls and three
		// transforms to keep in step.
		const int32 GroupCount = bMergeByNode ? 1 : ValidMeshIndices.Num();

		for (int32 GroupIndex = 0; GroupIndex < GroupCount; ++GroupIndex)
		{
			const TArray<int32> GroupIndices = bMergeByNode
				? ValidMeshIndices
				: TArray<int32>{ ValidMeshIndices[GroupIndex] };

			const FString ComponentName = FString::Printf(
				TEXT("AssimpMesh_%d_%d"), NodeIndex, GroupIndex);

			UDynamicMeshComponent* Component = NewObject<UDynamicMeshComponent>(
				Actor, MakeUniqueObjectName(Actor, UDynamicMeshComponent::StaticClass(), *ComponentName));

			if (Component == nullptr)
			{
				continue;
			}

			if (!SceneObject->BuildMergedDynamicMesh(GroupIndices, Component->GetDynamicMesh()))
			{
				// Building failed, so discard the component rather than attaching an empty one.
				Component->MarkAsGarbage();
				continue;
			}

			// Must happen before registration so the proxy is built with the slots already in place;
			// without any slot the primitive gets no material relevance and is never drawn.
			AssimpRuntimePrivate::AssignMaterialSlots(
				Component, SceneObject, Info, GroupIndices, BaseMaterial);

			Component->SetupAttachment(RootComponent);
			Component->RegisterComponent();
			Component->SetRelativeTransform(WorldTransforms[NodeIndex]);

			// Collision is off by default: generating it for arbitrary imported geometry is
			// expensive and rarely what a caller wants without asking.
			Component->SetCollisionEnabled(ECollisionEnabled::NoCollision);

			Created.Add(Component);
		}
	}

	UE_LOG(LogAssimpRuntime, Log,
		TEXT("Spawned %d dynamic mesh component(s) from '%s'."),
		Created.Num(), *Info.SourceFilePath);

	return Created;
}

TArray<USceneComponent*> UAssimpBlueprintLibrary::SpawnSceneCamerasAndLights(
	AActor* Actor,
	UAssimpSceneObject* SceneObject)
{
	TArray<USceneComponent*> Created;

	if (Actor == nullptr || SceneObject == nullptr || !SceneObject->IsValidScene())
	{
		UE_LOG(LogAssimpRuntime, Warning,
			TEXT("SpawnSceneCamerasAndLights called with an invalid actor or scene."));
		return Created;
	}

	const FAssimpSceneInfo& Info = SceneObject->GetSceneInfo();

	if (Info.Cameras.IsEmpty() && Info.Lights.IsEmpty())
	{
		return Created;
	}

	USceneComponent* RootComponent = Actor->GetRootComponent();

	// Same forward pass as the mesh spawner: a parent always precedes its children, so each node's
	// world transform is known by the time it is needed.
	TArray<FTransform> WorldTransforms;
	WorldTransforms.SetNum(Info.Nodes.Num());
	for (int32 NodeIndex = 0; NodeIndex < Info.Nodes.Num(); ++NodeIndex)
	{
		const FAssimpNodeInfo& Node = Info.Nodes[NodeIndex];
		WorldTransforms[NodeIndex] = Info.Nodes.IsValidIndex(Node.ParentIndex)
			? Node.LocalTransform * WorldTransforms[Node.ParentIndex]
			: Node.LocalTransform;
	}

	/** Composes a camera or light's own placement with the transform of the node carrying it. */
	auto ResolveTransform = [&Info, &WorldTransforms](int32 NodeIndex, const FTransform& LocalTransform)
	{
		return Info.Nodes.IsValidIndex(NodeIndex)
			? LocalTransform * WorldTransforms[NodeIndex]
			: LocalTransform;
	};

	/** Attaches, registers and places a freshly created component. */
	auto Attach = [RootComponent, &Created](USceneComponent* Component, const FTransform& Transform)
	{
		Component->SetupAttachment(RootComponent);
		Component->RegisterComponent();
		Component->SetRelativeTransform(Transform);
		Created.Add(Component);
	};

	// --- Cameras ---------------------------------------------------------------------------------
	for (int32 CameraIndex = 0; CameraIndex < Info.Cameras.Num(); ++CameraIndex)
	{
		const FAssimpCameraInfo& Camera = Info.Cameras[CameraIndex];

		UCameraComponent* Component = NewObject<UCameraComponent>(
			Actor,
			MakeUniqueObjectName(Actor, UCameraComponent::StaticClass(),
				*FString::Printf(TEXT("AssimpCamera_%d"), CameraIndex)));

		if (Component == nullptr)
		{
			continue;
		}

		// Unreal's FieldOfView is the horizontal angle in degrees, which is what the scene
		// description already carries.
		if (Camera.HorizontalFieldOfViewDegrees > 0.0f)
		{
			Component->SetFieldOfView(FMath::Clamp(Camera.HorizontalFieldOfViewDegrees, 1.0f, 170.0f));
		}

		// An aspect ratio of 0 means the file did not state one, in which case the component should
		// keep following the viewport rather than be locked to a fabricated value.
		if (Camera.AspectRatio > 0.0f)
		{
			Component->SetAspectRatio(Camera.AspectRatio);
			Component->SetConstraintAspectRatio(true);
		}

		Attach(Component, ResolveTransform(Camera.NodeIndex, Camera.LocalTransform));
	}

	// --- Lights ----------------------------------------------------------------------------------
	int32 SkippedLights = 0;

	for (int32 LightIndex = 0; LightIndex < Info.Lights.Num(); ++LightIndex)
	{
		const FAssimpLightInfo& Light = Info.Lights[LightIndex];

		const FName ComponentName(*FString::Printf(TEXT("AssimpLight_%d"), LightIndex));

		ULightComponent* Component = nullptr;

		switch (Light.Type)
		{
		case EAssimpLightType::Directional:
			Component = NewObject<UDirectionalLightComponent>(
				Actor, MakeUniqueObjectName(Actor, UDirectionalLightComponent::StaticClass(), ComponentName));
			break;

		case EAssimpLightType::Point:
			Component = NewObject<UPointLightComponent>(
				Actor, MakeUniqueObjectName(Actor, UPointLightComponent::StaticClass(), ComponentName));
			break;

		case EAssimpLightType::Spot:
			Component = NewObject<USpotLightComponent>(
				Actor, MakeUniqueObjectName(Actor, USpotLightComponent::StaticClass(), ComponentName));
			break;

		default:
			// Ambient and area lights have no component that means the same thing in Unreal. An
			// ambient term is not a light at all, and an area light's shape is the half of it that
			// matters, which the scene description does not carry. Substituting a point light for
			// either would silently change how the scene reads, so they are reported instead.
			++SkippedLights;
			continue;
		}

		if (Component == nullptr)
		{
			continue;
		}

		// Colour transfers; intensity does not. See the header for why.
		Component->SetLightColor(Light.DiffuseColor);

		if (USpotLightComponent* Spot = Cast<USpotLightComponent>(Component))
		{
			// Assimp states the FULL cone angle -- its own header notes the inner angle is 2*PI for
			// a point light -- while Unreal takes half-angles measured from the light's axis.
			Spot->SetInnerConeAngle(FMath::Clamp(Light.InnerConeAngleDegrees * 0.5f, 0.0f, 89.0f));
			Spot->SetOuterConeAngle(FMath::Clamp(Light.OuterConeAngleDegrees * 0.5f, 0.0f, 89.0f));
		}

		if (UPointLightComponent* Point = Cast<UPointLightComponent>(Component))
		{
			const float Radius = AssimpRuntimePrivate::ComputeAttenuationRadius(Light, Info.AppliedScale);
			if (Radius > 0.0f)
			{
				Point->SetAttenuationRadius(Radius);
			}
		}

		Attach(Component, ResolveTransform(Light.NodeIndex, Light.LocalTransform));
	}

	if (SkippedLights > 0)
	{
		UE_LOG(LogAssimpRuntime, Warning,
			TEXT("%d light(s) in '%s' are ambient or area lights and were not spawned: neither has an ")
			TEXT("Unreal component that means the same thing."),
			SkippedLights, *Info.SourceFilePath);
	}

	UE_LOG(LogAssimpRuntime, Log,
		TEXT("Spawned %d camera/light component(s) from '%s'."),
		Created.Num(), *Info.SourceFilePath);

	return Created;
}

bool UAssimpBlueprintLibrary::ExportSceneToFile(
	UAssimpSceneObject* SceneObject,
	const FString& FilePath,
	const FString& FormatId,
	FAssimpExportResult& OutResult)
{
	OutResult = FAssimpExportResult();

	if (SceneObject == nullptr || !SceneObject->IsValidScene())
	{
		OutResult.ErrorMessage = TEXT("No valid scene to export.");
		UE_LOG(LogAssimpRuntime, Warning, TEXT("%s"), *OutResult.ErrorMessage);
		return false;
	}

	const TSharedPtr<FAssimpScene> Scene = SceneObject->GetScene();
	if (!Scene.IsValid())
	{
		OutResult.ErrorMessage = TEXT("The scene object holds no parsed scene.");
		return false;
	}

	const FAssimpSceneInfo& Info = SceneObject->GetSceneInfo();

	// Converted up front and held for the duration: FAssimpExporter::FExportMesh borrows its mesh
	// description rather than copying, so every one of them has to outlive the export call.
	TArray<FMeshDescription> MeshDescriptions;
	MeshDescriptions.SetNum(Info.Meshes.Num());

	TArray<FAssimpExporter::FExportMesh> ExportMeshes;
	ExportMeshes.Reserve(Info.Meshes.Num());

	for (int32 MeshIndex = 0; MeshIndex < Info.Meshes.Num(); ++MeshIndex)
	{
		if (!Scene->GetMeshDescription(MeshIndex, MeshDescriptions[MeshIndex]))
		{
			// One unconvertible mesh should not lose the rest of the model.
			UE_LOG(LogAssimpRuntime, Warning,
				TEXT("Mesh %d ('%s') could not be converted and was left out of the export."),
				MeshIndex, *Info.Meshes[MeshIndex].Name);
			continue;
		}

		FAssimpExporter::FExportMesh ExportMesh;
		ExportMesh.Name = Info.Meshes[MeshIndex].Name;
		ExportMesh.MeshDescription = &MeshDescriptions[MeshIndex];

		ExportMeshes.Add(MoveTemp(ExportMesh));
	}

	if (ExportMeshes.IsEmpty())
	{
		OutResult.ErrorMessage = TEXT("The scene holds no mesh that could be converted for export.");
		UE_LOG(LogAssimpRuntime, Warning, TEXT("%s"), *OutResult.ErrorMessage);
		return false;
	}

	return FAssimpExporter::ExportMeshes(ExportMeshes, FilePath, FormatId, OutResult);
}

TArray<FAssimpExportFormat> UAssimpBlueprintLibrary::GetSupportedExportFormats()
{
	return FAssimpExporter::GetSupportedFormats();
}

TArray<FString> UAssimpBlueprintLibrary::GetSupportedImportExtensions()
{
	return FAssimpScene::GetSupportedExtensions();
}

bool UAssimpBlueprintLibrary::IsExtensionSupported(const FString& Extension)
{
	return FAssimpScene::IsExtensionSupported(Extension);
}

FString UAssimpBlueprintLibrary::GetAssimpVersion()
{
	if (!IAssimpCoreModule::IsAvailable())
	{
		return FString();
	}

	return IAssimpCoreModule::Get().GetAssimpVersionString();
}
